CREATE DATABASE sistema_login;
USE sistema_login;

CREATE TABLE usuario(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
usuario VARCHAR(100) NOT NULL,
senha VARCHAR(100) NOT NULL
);

SELECT* FROM usuario;